import { tokens } from './tokens';

const opacityToPercent = (opacity: string) =>
  `${Number.parseFloat(opacity) * 100}%`;

const brutalGridLight = `rgb(0 0 0 / ${opacityToPercent(tokens.brutalist.grid.lineOpacity.light)})`;
const brutalGridDark = `rgb(255 255 255 / ${opacityToPercent(tokens.brutalist.grid.lineOpacity.dark)})`;

export const cssVariables = {
  root: {
    '--color-white': tokens.colors.white,
    '--color-black': tokens.colors.black,
    '--color-gray-100': tokens.colors.gray[100],
    '--color-gray-300': tokens.colors.gray[300],
    '--color-gray-500': tokens.colors.gray[500],
    '--color-gray-800': tokens.colors.gray[800],
    '--color-neutral-900': tokens.colors.neutral[900],
    '--color-neutral-800': tokens.colors.neutral[800],
    '--color-neutral-700': tokens.colors.neutral[700],
    '--color-accent': tokens.colors.accent,
    '--brutalist-black': 'var(--color-black)',
    '--brutalist-white': 'var(--color-white)',
    '--brutalist-accent': 'var(--color-accent)',

    '--background': tokens.semantic.light.background,
    '--foreground': tokens.semantic.light.foreground,
    '--primary': tokens.semantic.light.primary,
    '--primary-foreground': tokens.semantic.light.primaryForeground,
    '--secondary': tokens.semantic.light.secondary,
    '--secondary-foreground': tokens.semantic.light.secondaryForeground,
    '--muted': tokens.semantic.light.muted,
    '--muted-foreground': tokens.semantic.light.mutedForeground,
    '--accent': tokens.semantic.light.accent,
    '--accent-foreground': tokens.semantic.light.accentForeground,
    '--destructive': tokens.semantic.light.destructive,
    '--destructive-foreground': tokens.semantic.light.destructiveForeground,
    '--card': tokens.semantic.light.card,
    '--card-foreground': tokens.semantic.light.cardForeground,
    '--popover': tokens.semantic.light.popover,
    '--popover-foreground': tokens.semantic.light.popoverForeground,
    '--outline': tokens.semantic.light.outline,
    '--outline-foreground': tokens.semantic.light.outlineForeground,
    '--outline-border': tokens.semantic.light.outlineBorder,
    '--border': tokens.semantic.light.border,
    '--input': tokens.semantic.light.input,
    '--ring': tokens.semantic.light.ring,
    '--sidebar': tokens.semantic.light.sidebar,
    '--sidebar-foreground': tokens.semantic.light.sidebarForeground,
    '--sidebar-primary': tokens.semantic.light.sidebarPrimary,
    '--sidebar-primary-foreground':
      tokens.semantic.light.sidebarPrimaryForeground,
    '--sidebar-accent': tokens.semantic.light.sidebarAccent,
    '--sidebar-accent-foreground':
      tokens.semantic.light.sidebarAccentForeground,
    '--sidebar-border': tokens.semantic.light.sidebarBorder,
    '--sidebar-ring': tokens.semantic.light.sidebarRing,
    '--chart-1': tokens.semantic.light.chart1,
    '--chart-2': tokens.semantic.light.chart2,
    '--chart-3': tokens.semantic.light.chart3,
    '--chart-4': tokens.semantic.light.chart4,
    '--chart-5': tokens.semantic.light.chart5,

    '--font-sans': tokens.base.font.sans,
    '--font-heading': tokens.base.font.heading,
    '--font-serif': tokens.base.font.serif,
    '--font-mono': tokens.base.font.mono,
    '--radius': tokens.base.radius,
    '--tracking-normal': tokens.base.tracking.normal,

    '--shadow-color': 'var(--color-black)',
    '--shadow-color-light': 'var(--color-white)',
    '--shadow-offset-sm': tokens.base.shadow.offset.sm,
    '--shadow-offset-md': tokens.base.shadow.offset.md,
    '--shadow-offset-lg': tokens.base.shadow.offset.lg,
    '--hover-opacity': tokens.base.interaction.hoverOpacity,

    '--brutal-canvas': tokens.brutalist.colors.light.canvas,
    '--brutal-emphasis': tokens.brutalist.colors.light.emphasis,
    '--brutal-panel': tokens.brutalist.colors.light.panel,
    '--brutal-ink': tokens.brutalist.colors.light.ink,
    '--brutal-ink-inverse': tokens.brutalist.colors.light.invertedInk,
    '--brutal-border-subtle': tokens.brutalist.border.subtle,
    '--brutal-border-default': tokens.brutalist.border.default,
    '--brutal-border-strong': tokens.brutalist.border.strong,
    '--brutal-track-label': tokens.brutalist.tracking.label,
    '--brutal-track-heading': tokens.brutalist.tracking.heading,
    '--brutal-track-kicker': tokens.brutalist.tracking.kicker,
    '--brutal-grid-size': tokens.brutalist.grid.size,
    '--brutal-grid-line': brutalGridLight,
  },
  dark: {
    '--background': tokens.semantic.dark.background,
    '--foreground': tokens.semantic.dark.foreground,
    '--primary': tokens.semantic.dark.primary,
    '--primary-foreground': tokens.semantic.dark.primaryForeground,
    '--secondary': tokens.semantic.dark.secondary,
    '--secondary-foreground': tokens.semantic.dark.secondaryForeground,
    '--muted': tokens.semantic.dark.muted,
    '--muted-foreground': tokens.semantic.dark.mutedForeground,
    '--accent': tokens.semantic.dark.accent,
    '--accent-foreground': tokens.semantic.dark.accentForeground,
    '--destructive': tokens.semantic.dark.destructive,
    '--destructive-foreground': tokens.semantic.dark.destructiveForeground,
    '--card': tokens.semantic.dark.card,
    '--card-foreground': tokens.semantic.dark.cardForeground,
    '--popover': tokens.semantic.dark.popover,
    '--popover-foreground': tokens.semantic.dark.popoverForeground,
    '--outline': tokens.semantic.dark.outline,
    '--outline-foreground': tokens.semantic.dark.outlineForeground,
    '--outline-border': tokens.semantic.dark.outlineBorder,
    '--border': tokens.semantic.dark.border,
    '--input': tokens.semantic.dark.input,
    '--ring': tokens.semantic.dark.ring,
    '--sidebar': tokens.semantic.dark.sidebar,
    '--sidebar-foreground': tokens.semantic.dark.sidebarForeground,
    '--sidebar-primary': tokens.semantic.dark.sidebarPrimary,
    '--sidebar-primary-foreground':
      tokens.semantic.dark.sidebarPrimaryForeground,
    '--sidebar-accent': tokens.semantic.dark.sidebarAccent,
    '--sidebar-accent-foreground': tokens.semantic.dark.sidebarAccentForeground,
    '--sidebar-border': tokens.semantic.dark.sidebarBorder,
    '--sidebar-ring': tokens.semantic.dark.sidebarRing,
    '--chart-1': tokens.semantic.dark.chart1,
    '--chart-2': tokens.semantic.dark.chart2,
    '--chart-3': tokens.semantic.dark.chart3,
    '--chart-4': tokens.semantic.dark.chart4,
    '--chart-5': tokens.semantic.dark.chart5,
    '--shadow-color': 'var(--color-white)',
    '--shadow-color-light': 'var(--color-black)',
    '--brutal-canvas': tokens.brutalist.colors.dark.canvas,
    '--brutal-emphasis': tokens.brutalist.colors.dark.emphasis,
    '--brutal-panel': tokens.brutalist.colors.dark.panel,
    '--brutal-ink': tokens.brutalist.colors.dark.ink,
    '--brutal-ink-inverse': tokens.brutalist.colors.dark.invertedInk,
    '--brutal-grid-line': brutalGridDark,
  },
} as const;
