export const tokens = {
  colors: {
    white: '#ffffff',
    black: '#000000',
    accent: '#ff0000',
    gray: {
      100: '#eeeeee',
      300: '#cccccc',
      500: '#888888',
      800: '#333333',
    },
    neutral: {
      700: '#444444',
      800: '#1a1a1a',
      900: '#0a0a0a',
    },
    red: {
      400: '#ff3333',
      500: '#ff1e1e',
      600: '#ff0000',
    },
  },
  base: {
    font: {
      sans:
        '"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      heading:
        '"Bricolage Grotesque", "Inter", system-ui, -apple-system, sans-serif',
      serif: '"Playfair Display", Georgia, serif',
      mono: '"Space Mono", ui-monospace, "Courier New", monospace',
    },
    radius: '0rem',
    tracking: {
      normal: '0',
    },
    interaction: {
      hoverOpacity: '0.8',
    },
    shadow: {
      offset: {
        sm: '2px',
        md: '4px',
        lg: '8px',
      },
    },
  },
  brutalist: {
    colors: {
      light: {
        canvas: '#f5f3ee',
        emphasis: '#ffe500',
        panel: '#ffffff',
        ink: '#000000',
        invertedInk: '#ffffff',
      },
      dark: {
        canvas: '#171717',
        emphasis: '#ffe500',
        panel: '#0a0a0a',
        ink: '#ffffff',
        invertedInk: '#000000',
      },
    },
    border: {
      subtle: '2px',
      default: '3px',
      strong: '4px',
    },
    tracking: {
      label: '0.06em',
      heading: '0.08em',
      kicker: '0.12em',
    },
    grid: {
      size: '32px',
      lineOpacity: {
        light: '0.08',
        dark: '0.09',
      },
    },
  },
  semantic: {
    light: {
      background: 'var(--color-white)',
      foreground: 'var(--color-black)',
      primary: 'var(--color-black)',
      primaryForeground: 'var(--color-white)',
      secondary: 'var(--color-white)',
      secondaryForeground: 'var(--color-black)',
      muted: 'var(--color-gray-100)',
      mutedForeground: 'var(--color-black)',
      accent: 'var(--brutal-emphasis)',
      accentForeground: 'var(--color-black)',
      destructive: 'var(--color-accent)',
      destructiveForeground: 'var(--color-white)',
      card: 'var(--color-white)',
      cardForeground: 'var(--color-black)',
      popover: 'var(--color-white)',
      popoverForeground: 'var(--color-black)',
      outline: 'var(--color-white)',
      outlineForeground: 'var(--color-black)',
      outlineBorder: 'var(--color-black)',
      border: 'var(--color-black)',
      input: 'var(--color-gray-300)',
      ring: 'var(--color-black)',
      sidebar: 'var(--color-white)',
      sidebarForeground: 'var(--color-black)',
      sidebarPrimary: 'var(--color-black)',
      sidebarPrimaryForeground: 'var(--color-white)',
      sidebarAccent: 'var(--brutal-emphasis)',
      sidebarAccentForeground: 'var(--color-black)',
      sidebarBorder: 'var(--color-black)',
      sidebarRing: 'var(--color-black)',
      chart1: 'var(--color-black)',
      chart2: 'var(--color-accent)',
      chart3: 'var(--color-gray-500)',
      chart4: 'var(--color-gray-300)',
      chart5: 'var(--color-gray-800)',
    },
    dark: {
      background: 'var(--color-neutral-900)',
      foreground: 'var(--color-white)',
      primary: 'var(--color-white)',
      primaryForeground: 'var(--color-black)',
      secondary: 'var(--color-neutral-900)',
      secondaryForeground: 'var(--color-white)',
      muted: 'var(--color-neutral-800)',
      mutedForeground: 'var(--color-white)',
      accent: 'var(--brutal-emphasis)',
      accentForeground: 'var(--color-black)',
      destructive: 'var(--color-accent)',
      destructiveForeground: 'var(--color-white)',
      card: 'var(--color-neutral-900)',
      cardForeground: 'var(--color-white)',
      popover: 'var(--color-neutral-900)',
      popoverForeground: 'var(--color-white)',
      outline: 'transparent',
      outlineForeground: 'var(--color-white)',
      outlineBorder: 'var(--color-white)',
      border: 'var(--color-white)',
      input: 'var(--color-neutral-700)',
      ring: 'var(--color-white)',
      sidebar: 'var(--color-neutral-900)',
      sidebarForeground: 'var(--color-white)',
      sidebarPrimary: 'var(--color-white)',
      sidebarPrimaryForeground: 'var(--color-black)',
      sidebarAccent: 'var(--brutal-emphasis)',
      sidebarAccentForeground: 'var(--color-black)',
      sidebarBorder: 'var(--color-white)',
      sidebarRing: 'var(--color-white)',
      chart1: 'var(--color-white)',
      chart2: 'var(--color-accent)',
      chart3: 'var(--color-gray-500)',
      chart4: 'var(--color-neutral-700)',
      chart5: 'var(--color-gray-300)',
    },
  },
} as const;

export type DesignTokens = typeof tokens;
